name: Workflow to remove EKS Cluster and associated resources

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: dev
        type: choice
        options:
          - prod
          - dev

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Set Working Directory
        run: echo "WORKING_DIR=./environment/${{ inputs.environment }}" >> $GITHUB_ENV

      - name: Configure AWS Credentials (Access Keys)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.TF_VAR_region }}
      
      # Run Terraform commands using the dynamic directory set above
      - name: Terraform Init
        run: terraform init
        working-directory: ./environment/${{ inputs.environment }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./environment/${{ inputs.environment }}
      
